version: '2'

services:
  db:
    image: mysql:latest
    command: mysqld --user=root
    volumes:
      - ${MYSQL_DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: webserver
      MYSQL_USER: bammmotif_admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis_celery:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DB_DIR}:/data

  celery:
    build: .
    command: dumb-init --single-child bash ./run_workers.sh
    user: ${BAMM_USER_UID}
    volumes:
      - ${WEBSERVER_DIR}:/code
      - ${MEDIA_DIR}:/code/media
      - ${MOTIF_DB_DIR}:/motif_db
      - ${LOG_DIR}:/logs
      - ${BACKUP_DIR}:/backup
    links:
      - redis_celery
      - db
    environment: &env_vars
        - DJANGO_DEBUG=${DJANGO_DEBUG}
        - BAMM_LOG_LEVEL=${BAMM_LOG_LEVEL}
        - SECRET_KEY=${SECRET_KEY}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_STARTUP_DELAY_SECONDS=${MYSQL_STARTUP_DELAY_SECONDS}
        - DEFAULT_MOTIF_DB=${DEFAULT_MOTIF_DB}
        - MAX_FINDJOB_DAYS=${MAX_FINDJOB_DAYS}
        - MAX_UPLOAD_FILE_SIZE=${MAX_UPLOAD_FILE_SIZE}
        - JOB_TIME_LIMIT=${JOB_TIME_LIMIT}
        - N_PARALLEL_JOBS=${N_PARALLEL_JOBS}
        - N_CORES_PER_JOB=${N_CORES_PER_JOB}
        - MAX_SEEDS_FOR_REFINEMENT=${MAX_SEEDS_FOR_REFINEMENT} 
        - DEFAULT_SEEDS_FOR_REFINEMENT=${DEFAULT_SEEDS_FOR_REFINEMENT}
        - FORCE_EXAMPLE_CREATION=${FORCE_EXAMPLE_CREATION} 
        - ZIP_INCLUDE_ZOOPS_STATS=${ZIP_INCLUDE_ZOOPS_STATS} 
        - MIN_FASTA_SEQUENCES=${MIN_FASTA_SEQUENCES}
        - EMAIL_LOGGER_LEVEL=${EMAIL_LOGGER_LEVEL}
        - EMAIL_LOGGER_SERVER=${EMAIL_LOGGER_SERVER}
        - EMAIL_LOGGER_PORT=${EMAIL_LOGGER_PORT}
        - EMAIL_LOGGER_FROM=${EMAIL_LOGGER_FROM}
        - EMAIL_LOGGER_TO=${EMAIL_LOGGER_TO}
        - EMAIL_LOGGER_USER=${EMAIL_LOGGER_USER}
        - EMAIL_LOGGER_PASSWORD=${EMAIL_LOGGER_PASSWORD}
        - EMAIL_LOGGER_USE_TLS=${EMAIL_LOGGER_USE_TLS}
        - EMAIL_LOGGER_SUBJECT=${EMAIL_LOGGER_SUBJECT}
        - FDR_CV_FOLD=${FDR_CV_FOLD}
        - MAX_INPUT_STORAGE_DAYS=${MAX_INPUT_STORAGE_DAYS}
        - MAX_JOB_STORAGE_DAYS=${MAX_JOB_STORAGE_DAYS}
        - N_STORED_BACKUPS=${N_STORED_BACKUPS}

  web:
    build: .
    command: /usr/local/bin/dumb-init -- ./run_web.sh
    user: ${BAMM_USER_UID}
    environment:
      - EXAMPLE_MOTIF_DB=${EXAMPLE_MOTIF_DB}
    volumes:
      - ${WEBSERVER_DIR}:/code
      - ${MEDIA_DIR}:/code/media
      - ${MOTIF_DB_DIR}:/motif_db
      - ${LOG_DIR}:/logs
      - ${BACKUP_DIR}:/backup
    ports:
      - ${SERVER_HOST_PORT}:10080
    links:
      - db
      - redis_celery
      - celery
    environment: *env_vars
